require "active_record"
require "active_support/lazy_load_hooks"

require "active_record/associations/builder/may_belong_to"
require "active_record/associations/preloader/may_belong_to"
require "active_record/may_belong_to/association_reflection"
require "active_record/may_belong_to/class_methods"
require "active_record/may_belong_to/preloader_extension"
require "active_record/may_belong_to/reflection_extension"
require "active_record/may_belong_to/version"
require "active_record/may_belong_to/ext"
